server:
  port: 8088
#rocketmq配置
rocketmq:
  nameServer: 192.168.1.14:9876
  # 生产者配置
  producer:
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    group: niuml-rocketmq-group
    groupName: niuml-rocketmq-group
    # 服务地址
    namesrvAddr: 192.168.1.14:9876
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
